--[[ keybindings.lua ]]

local map = vim.api.nvim_set_keymap

--          === Normal ===
map('n', '<leader><leader>', ':', {noremap = true})
map('n', ',,', 'vip', {noremap = true})
map('n', 'vik', 'vi)', {noremap = true})
map('n', 'vif', 'vi]', {noremap = true})
map('n', 'vih', 'vi}', {noremap = true})
map('n', 'vis', 'vi\'', {noremap = true})
map('n', 'vid', 'vi"', {noremap = true})
map('n', 'dik', 'di)', {noremap = true})
map('n', 'dif', 'di]', {noremap = true})
map('n', 'dih', 'di}', {noremap = true})
map('n', 'dis', 'di\'', {noremap = true})
map('n', 'did', 'di"', {noremap = true})
map('n', 'cik', 'ci)', {noremap = true})
map('n', 'cif', 'ci]', {noremap = true})
map('n', 'cih', 'ci}', {noremap = true})
map('n', 'cis', 'ci\'', {noremap = true})
map('n', 'cid', 'ci"', {noremap = true})
map('n', 'dsk', 'ds)', {noremap = true})
map('n', 'dsf', 'ds]', {noremap = true})
map('n', 'dsh', 'ds}', {noremap = true})
map('n', 'dss', 'ds\'', {noremap = true})
map('n', 'dsd', 'ds"', {noremap = true})
map('n', 'gor', ':%s/', {noremap = true})
map('n', 'goo', '==', {noremap = true})
map('n', 'gol', '^vg_', {noremap = true})
map('n', 'goi', 'gg0vG$=<C-o>', {noremap = true})
map('n', ',k', 'viwS)', {})
map('n', ',f', 'viwS]', {})
map('n', ',h', 'viwS}', {})
map('n', ',s', 'viwS\'', {})
map('n', ',d', 'viwS"', {})
-- Movement
map('n', ';a', '0', {noremap = true})
map('n', ';e', '$', {noremap = true})
-- Close
map('n', '<leader>qq', ':q<CR>', {noremap = true})
-- Files
map('n', '<leader>fs', ':w<CR>', {noremap = true})
map('n', '<leader>fn', ':tabedit<CR>', {noremap = true})
-- Buffers
map('n', '<leader>bd', ':bd<CR>', {noremap = true})
map('n', '<leader>bn', ':bn<CR>', {noremap = true})
map('n', '<leader>bp', ':bp<CR>', {noremap = true})
map('n', '<leader>bh', 'gg0vG$', {noremap = true})
-- Windows
map('n', '<leader>ws', ':split<CR><C-w>w', {noremap = true})
map('n', '<leader>wv', ':vsplit<CR><C-w>w', {noremap = true})
map('n', '<leader>wh', '<C-w>h', {noremap = true})
map('n', '<leader>wl', '<C-w>l', {noremap = true})
map('n', '<leader>wj', '<C-w>j', {noremap = true})
map('n', '<leader>wk', '<C-w>k', {noremap = true})
-- Tabs
map('n', '<leader>tf', ':tabf<Space>', {noremap = true})
map('n', '<leader>te', ':tabe<CR>', {noremap = true})
map('n', '<leader>to', ':tabonly<CR>', {noremap = true})
map('n', '<leader>td', ':tabclose<CR>', {noremap = true})
map('n', '<leader>tD', ':tabclose!<CR>', {noremap = true})
map('n', '<leader>1', ':BufferLineGoToBuffer 1<CR>', {noremap = true})
map('n', '<leader>2', ':BufferLineGoToBuffer 2<CR>', {noremap = true})
map('n', '<leader>3', ':BufferLineGoToBuffer 3<CR>', {noremap = true})
-- Packeages
map('n', '<leader>pl', ':Lazy<CR>', {noremap = true})

--          === Visual ===
map('v', 'gor', ':s/', {noremap = true})
map('v', 'goo', '=', {noremap = true})
map('v', ',k', 'S)', {noremap = true})
map('v', ',f', 'S]', {noremap = true})
map('v', ',h', 'S}', {noremap = true})
map('v', ',s', 'S\'', {noremap = true})
map('v', ',d', 'S"', {noremap = true})
map('v', ',,', 'ip', {noremap = true})
map('v', '<C-g>', '<Escape>', {noremap = true})
-- Remap the key used to leave visual mode
map('v', 'fd', '<Escape>', {noremap = true})
-- Movement
map('v', ';a', '0', {noremap = true})
map('v', ';e', '$', {noremap = true})


--          === Insert ===
map('i', '<C-g>', '<Escape>', {noremap = true})
-- Remap the key used to leave insert mode
map('i', 'fd', '<Escape>', {noremap = true})
-- Move cursor forward in insert mode
map('i', '<C-f>', '<right>', {noremap = true})
-- Move cursor backward in insert mode
map('i', '<C-b>', '<left>', {noremap = true})
-- Backwards delete char
map('i', '<C-k>', '<C-h>', {noremap = true})
-- Key chord
map('i', 'kk', '()<C-b>', {})
map('i', ',,', '[]<C-b>', {})
map('i', 'hh', '{}<C-b>', {})
map('i', 'ji', '-', {noremap = true})
map('i', 'jj', '+', {noremap = true})
map('i', 'uu', '_', {noremap = true})
map('i', 'aa', '&', {noremap = true})
map('i', 'vv', '#', {noremap = true})
map('i', 'bb', '~', {noremap = true})
map('i', 'ww', '?', {noremap = true})
map('i', 'gt', '!', {noremap = true})
map('i', 'zl', '|', {noremap = true})
map('i', 'fh', '%', {noremap = true})
map('i', 'cj', '*', {noremap = true})
map('i', 'dh', '=', {noremap = true})
map('i', 'fh', '%', {noremap = true})
map('i', ';x', '<', {noremap = true})
map('i', ';d', '>', {noremap = true})
map('i', ';h', '<><C-b>', {})
map('i', 'mj', '$', {noremap = true})
map('i', 'yb', '£', {noremap = true})
map('i', ';c', '^', {noremap = true})
map('i', ';f', '5', {noremap = true})
map('i', ';i', '6', {noremap = true})
map('i', ';s', '7', {noremap = true})
map('i', ';e', '8', {noremap = true})
map('i', ';n', '9', {noremap = true})
map('i', ';t', '0', {noremap = true})
map('i', ',d', '==', {noremap = true})


--          === Command ===
map('c', '<C-k>', '<C-h>', {noremap = true})
map('c', '<C-g>', '<C-u><C-h>', {noremap = true})
map('c', '<C-f>', '<right>', {noremap = true})
map('c', '<C-b>', '<left>', {noremap = true})
map('c', 'kk', '()<C-b>', {noremap = true})
map('c', ',,', '[]<C-b>', {noremap = true})
map('c', 'hh', '{}<C-b>', {noremap = true})
map('c', 'ji', '-', {noremap = true})
map('c', 'jj', '+', {noremap = true})
map('c', 'uu', '_', {noremap = true})
map('c', 'aa', '&', {noremap = true})
map('c', 'vv', '#', {noremap = true})
map('c', 'bb', '~', {noremap = true})
map('c', 'ww', '?', {noremap = true})
map('c', 'cj', '*', {noremap = true})
map('c', 'dh', '=', {noremap = true})
map('c', 'fh', '%', {noremap = true})
map('c', ';x', '<', {noremap = true})
map('c', ';d', '>', {noremap = true})
map('c', ';h', '<><C-b>', {noremap = true})
map('c', 'mj', '$', {noremap = true})
map('c', 'yb', '£', {noremap = true})
map('c', ';f', '5', {noremap = true})
map('c', ';i', '6', {noremap = true})
map('c', ';s', '7', {noremap = true})
map('c', ';e', '8', {noremap = true})
map('c', ';n', '9', {noremap = true})
map('c', ';t', '0', {noremap = true})


--          === Terminal ===
-- switch to normal mode in terminal
map('t', '<C-g>', '<C-\\><C-n>', {noremap = true})
map('t', '<C-k>', '<C-h>', {noremap = true})
map('t', 'kk', '()<C-b>', {noremap = true})
map('t', ',,', '[]<C-b>', {noremap = true})
map('t', 'hh', '{}<C-b>', {noremap = true})
map('t', 'ji', '-', {noremap = true})
map('t', 'jj', '+', {noremap = true})
map('t', 'uu', '_', {noremap = true})
map('t', 'aa', '&', {noremap = true})
map('t', 'vv', '#', {noremap = true})
map('t', 'bb', '~', {noremap = true})
map('t', 'ww', '?', {noremap = true})
map('t', 'cj', '*', {noremap = true})
map('t', 'dh', '=', {noremap = true})
map('t', 'fh', '%', {noremap = true})
map('t', ';x', '<', {noremap = true})
map('t', ';d', '>', {noremap = true})
map('t', ';h', '<><C-b>', {noremap = true})
map('t', 'mj', '$', {noremap = true})
map('t', 'yb', '£', {noremap = true})
map('t', ';f', '5', {noremap = true})
map('t', ';i', '6', {noremap = true})
map('t', ';s', '7', {noremap = true})
map('t', ';e', '8', {noremap = true})
map('t', ';n', '9', {noremap = true})
map('t', ';t', '0', {noremap = true})
