--[[ keybindings.lua ]]
local map = vim.api.nvim_set_keymap


--          === Normal ===
map('n', ',,', 'vip', {})
map('n', 'vik', 'vi)', {})
map('n', 'vif', 'vi]', {})
map('n', 'vih', 'vi}', {})
map('n', 'vis', 'vi\'', {})
map('n', 'vid', 'vi"', {})
map('n', 'cik', 'ci)', {})
map('n', 'cif', 'ci]', {})
map('n', 'cih', 'ci}', {})
map('n', 'cis', 'ci\'', {})
map('n', 'cid', 'ci"', {})
map('n', 'dsk', 'ds)', {})
map('n', 'dsf', 'ds]', {})
map('n', 'dsh', 'ds}', {})
map('n', 'dss', 'ds\'', {})
map('n', 'dsd', 'ds"', {})
map('n', 'gor', ':%s/', {})
map('n', 'gof', '==', {})
-- Movement
map('n', ';a', '0', {})
map('n', ';e', '$', {})
-- Close
map('n', '<leader>qq', ':q<CR>', {})
-- Files
map('n', '<leader>fs', ':w<CR>', {})
map('n', '<leader>fn', ':tabedit<CR>', {})
-- Buffers
map('n', '<leader>bd', ':bd<CR>', {})
map('n', '<leader>bn', ':bn<CR>', {})
map('n', '<leader>bp', ':bp<CR>', {})
map('n', '<leader>bw', 'gg0vG$', {})
-- Windows
map('n', '<leader>ws', ':split<CR><C-w>w', {})
map('n', '<leader>wv', ':vsplit<CR><C-w>w', {})
map('n', '<leader>wh', '<C-w>h', {})
map('n', '<leader>wl', '<C-w>l', {})
map('n', '<leader>wj', '<C-w>j', {})
map('n', '<leader>wk', '<C-w>k', {})
-- Tabs
map('n', '<leader>tf', ':tabf<Space>', {})
map('n', '<leader>te', ':tabe<CR>', {})
map('n', '<leader>to', ':tabonly<CR>', {})
map('n', '<leader>td', ':tabclose<CR>', {})
map('n', '<leader>tD', ':tabclose!<CR>', {})
map('n', '<leader>1', ':BufferLineGoToBuffer 1<CR>', {})
map('n', '<leader>2', ':BufferLineGoToBuffer 2<CR>', {})
map('n', '<leader>3', ':BufferLineGoToBuffer 3<CR>', {})
-- Packeages
map('n', '<leader>pi', ':PackerInstall<CR>', {silent = true})
map('n', '<leader>pu', ':PackerUpdate<CR>', {silent = true})
map('n', '<leader>pS', ':PackerStatus<CR>', {silent = true})
map('n', '<leader>ps', ':PackerSync<CR>', {silent = true})
map('n', '<leader>pc', ':PackerClean<CR>', {silent = true})
-- Repl
map('n', ';jj', ':IronRepl<CR>', {}) 
map('n', ';jR', ':IronRestart<CR>', {})
map('n', ';jf', ':IronFocus<CR>', {})
map('n', ';jh', ':IronHide<CR>', {})


--          === Visual ===
map('v', 'gor', ':s/', {})
map('v', 'gof', '=', {})
map('v', ',k', 'S)', {})
map('v', ',f', 'S]', {})
map('v', ',h', 'S}', {})
map('v', ',s', 'S\'', {})
map('v', ',d', 'S"', {})
map('v', ',,', 'ip', {})
map('v', '<C-g>', '<Escape>', {})
-- Remap the key used to leave visual mode
map('v', 'fd', '<Escape>', {})
-- Movement
map('v', ';a', '0', {})
map('v', ';e', '$', {})


--          === Insert ===
map('i', '<C-g>', '<Escape>', {})
-- Remap the key used to leave insert mode
map('i', 'fd', '<Escape>', {})
-- Move cursor forward in insert mode
map('i', '<C-f>', '<right>', {})
-- Move cursor backward in insert mode
map('i', '<C-b>', '<left>', {})
-- Backwards delete char
map('i', '<C-k>', '<C-h>', {})
-- Key chord
map('i', 'kk', '()<C-b>', {})
map('i', ',,', '[]<C-b>', {})
map('i', 'hh', '{}<C-b>', {})
map('i', 'ji', '-', {})
map('i', 'jj', '+', {})
map('i', 'uu', '_', {})
map('i', 'aa', '&', {})
map('i', 'vv', '#', {})
map('i', 'bb', '~', {})
map('i', 'ww', '?', {})
map('i', 'cj', '*', {})
map('i', 'dh', '=', {})
map('i', 'xy', '<', {})
map('i', 'dy', '>', {})
map('i', 'mj', '$', {})
map('i', 'yb', '£', {})
map('i', ';f', '5', {})
map('i', ';i', '6', {})
map('i', ';s', '7', {})
map('i', ';e', '8', {})
map('i', ';n', '9', {})
map('i', ';t', '0', {})


--          === Command ===
map('c', '<C-k>', '<C-h>', {})
map('c', '<C-g>', '<C-u><C-h>', {})
map('c', '<C-f>', '<right>', {})
map('c', '<C-b>', '<left>', {})
map('c', 'kk', '()<C-b>', {})
map('c', ',,', '[]<C-b>', {})
map('c', 'hh', '{}<C-b>', {})
map('c', 'ji', '-', {})
map('c', 'jj', '+', {})
map('c', 'uu', '_', {})
map('c', 'aa', '&', {})
map('c', 'vv', '#', {})
map('c', 'bb', '~', {})
map('c', 'ww', '?', {})
map('c', 'cj', '*', {})
map('c', 'dh', '=', {})
map('c', 'xy', '<', {})
map('c', 'dy', '>', {})
map('c', 'mj', '$', {})
map('c', 'yb', '£', {})
map('c', ';f', '5', {})
map('c', ';i', '6', {})
map('c', ';s', '7', {})
map('c', ';e', '8', {})
map('c', ';n', '9', {})
map('c', ';t', '0', {})


--          === Terminal ===
-- switch to normal mode in terminal
map('t', '<C-g>', '<C-\\><C-n>', {})
map('t', '<C-k>', '<C-h>', {})
map('t', 'kk', '()<C-b>', {})
map('t', ',,', '[]<C-b>', {})
map('t', 'hh', '{}<C-b>', {})
map('t', 'ji', '-', {})
map('t', 'jj', '+', {})
map('t', 'uu', '_', {})
map('t', 'aa', '&', {})
map('t', 'vv', '#', {})
map('t', 'bb', '~', {})
map('t', 'ww', '?', {})
map('t', 'cj', '*', {})
map('t', 'dh', '=', {})
map('t', 'xy', '<', {})
map('t', 'dy', '>', {})
map('t', 'mj', '$', {})
map('t', 'yb', '£', {})
map('t', ';f', '5', {})
map('t', ';i', '6', {})
map('t', ';s', '7', {})
map('t', ';e', '8', {})
map('t', ';n', '9', {})
map('t', ';t', '0', {})
